### PR TITLE
Add "flip" argument to ledGrid() and ledGrid8x8()

### PR DESCRIPTION
**Pull request by hobzcalvin**
The "zigzag" argument is handy to create daisy-chained grids, but what
if we want to start from the other side? I don't think rotation gets us
there, but this does.

### CODE REVIEW

**Comment by scanlime** [comment]
Hi! I appreciate the patch. Are there commonly available premade grids that need this option? If so, I'd rather add a new (possibly more general) variant of ledGrid rather than changing the existing functions in an incompatible way.

**Comment by hobzcalvin** [comment]
Hi, thanks for Fadecandy! I would think that any premade grid could be oriented in such a way that pixel 0 is top-left, as in my (admittedly custom) setup.
Regarding compatibility, I don't suppose overloading ledGrid is a better solution in your opinion? I'd be happy to add an overloaded version that introduces this "flip" argument so that existing clients don't need to update, but I thought that too might be an undesirable practice.
Either way, I figure that any user of the zigzag option would want to choose in which orientation the zigzag starts. (The rotation argument gets us part of the way there.)

**Comment by scanlime** [comment]
The reason I ask how common these grids are: the intention behind this API
is that if you're placing the LEDs yourself (on a board or otherwise) you
can write your own loop (copy and modify the ledGrid function) but if
you're using a common layout there are convenience functions to support
those. ledGrid() isn't intended to handle every possible thing, rather it's
handling the really common cases.

**Comment by briggsm** [comment]
I was going to create a pull request, but I saw this one, and I believe it's the same as what I wanted to propose....  I bought this 8x8 RGB LED board:
[http://www.seeedstudio.com/depot/88-RGB-LED-Matrix-w-WS2812B-DC-5V-p-2371.html](http://www.seeedstudio.com/depot/88-RGB-LED-Matrix-w-WS2812B-DC-5V-p-2371.html)

It doesn't say in the spec online, but its LED layout is as follows:
```
0 15 16 31 32 47 48 63
1 14 17 30 33 46 49 62
2 13 18 29 34 45 50 61
3 12 19 28 35 44 51 60
4 11 20 27 36 43 52 59
5 10 21 26 37 42 53 58
6  9 22 25 38 41 54 57
7  8 23 24 39 40 55 56
```

The current code does not handle this matrix layout by default.  The code assumes if you start with pixel0 in the upper-left corner, then pixel1 will be to the RIGHT of it.  But in the above board, pixel1 if BELOW pixel0.

This was my fix (not sure if it's functionally the same or different from what hobzcalvin posted):
```
void ledGrid(int index, int stripLength, int numStrips, float x, float y,
           float ledSpacing, float stripSpacing, float angle, boolean zigzag, boolean ltr)
{
 float s = sin(angle + HALF_PI);
 float c = cos(angle + HALF_PI);
 for (int i = 0; i < numStrips; i++) {
  opc.ledStrip(index + stripLength * i, stripLength,
      x + (i - (numStrips-1)/2.0) * stripSpacing * (ltr ? c : s),
      y + (i - (numStrips-1)/2.0) * stripSpacing * (ltr ? s : c), ledSpacing,
      ltr ? angle : (angle + HALF_PI), zigzag && (i % 2) == 1);
 }
}

void ledGrid8x8(int index, float x, float y, float spacing, float angle, boolean zigzag, boolean ltr)
{
  ledGrid(index, 8, 8, x, y, spacing, spacing, angle, zigzag, ltr);
}
```

I called my boolean 'ltr' for "left to right" - if it's true then do as usual, if false then go from top to bottom. There's probably a better choice for variable name....

Anyhow, Micah, I read your comments above & it looks like you might not be too keen on putting this in the library, and I can understand your reasoning.  I just wanted to post as well, and link to an actual board that I happened to run across that others may buy too, and have troubles getting it up & running properly....  And I would think it would be a good thing to allow the user to specify which way their pixels flow (left-to-right, or top-to-bottom (starting with Pixel0 in the upper-left)).

Another thought: if you aren't willing to put it in the library, then maybe somewhere in the tutorials.  I searched high & low for a solution to this before coming up with my own.  I couldn't find anything - though I guess maybe that means not many people are using these 'unique' boards....

And just for reference, here's the post I wrote last night on the wiki which has a few more details: [https://groups.google.com/d/topic/fadecandy/OcKnPXjuXUQ/discussion](https://groups.google.com/d/topic/fadecandy/OcKnPXjuXUQ/discussion)

And, I almost forgot, THANK YOU so much for fadecandy!  Super well-made & a beautiful product!!!

**Comment by briggsm** [comment]
Just for completeness, when I physically rotated my board, my algorithm didn't work (it was mirrored). hobzcalvin's algorithm worked through all rotations.

**Comment by jlgangwisch** [comment]
Hi!  Came here for flip functionality, was not disappointed.  Thank you all!  I bought a bunch of 8x8 flexible grids from China, first addressable LED project, this seems to be what I needed.

**Comment by hobzcalvin** [comment]
Hi @jlgangwisch! ...does that mean you used my commit? Another vote to merge in this PR, @scanlime?

**Comment by jlgangwisch** [comment]
I think I've put my foot in it now- I did use your commit, but it didn't do what I expected it to!  I'm brand new to addressable LEDs (and electronics to be honest), so I only barely understand what I'm doing.  Turns out what I needed was to change the LED strip function:

```
    float s = sin(angle + HALF_PI);
to
    float s = sin(angle - HALF_PI);
```

I ended up typing your commit changes into my code, so there's a chance I did something wrong and that's why I got screwy results.  Regardless, I definitely vote for incorporating your changes, whether or not they worked for me.  They definitely set me on the right path.

**Pull request merged**
